image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - "cd src/cappanna-helper-api"
    - "dotnet restore -v q"

build:
    stage: build
    script:
        - "dotnet build -v q"

test:
    stage: test
    script:
        - "dotnet test /p:CollectCoverage=true /p:CoverletOutput=\"./../coverage/\" /p:Exclude=\"[xunit.*]*%2c[*]*Tests*\" ./CappannaHelper.Printing.Tests/CappannaHelper.Printing.Tests.csproj"
        - "dotnet test /p:CollectCoverage=true /p:MergeWith=\"./../coverage/coverage.json\" /p:CoverletOutput=\"./../coverage/\" /p:CoverletOutputFormat=lcov /p:Exclude=\"[xunit.*]*%2c[*]*Tests*\" ./CappannaHelper.Api.Tests/CappannaHelper.Api.Tests.csproj"
        