export const SIGNIN_REQUESTED = "SIGNIN_REQUESTED";
export const SIGNIN_COMPLETED = "SIGNIN_COMPLETED";
export const SIGNOUT_REQUESTED = "SIGNOUT_REQUESTED";
export const SIGNOUT_COMPLETED = "SIGNOUT_COMPLETED";
export const SIGNUP_REQUESTED = "SIGNUP_REQUESTED";
export const SIGNUP_COMPLETED = "SIGNUP_COMPLETED";
export const LOAD_USER_DATA = "LOAD_USER_DATA";

export const LOADING_CHANGED = "LOADING_CHANGED";
export const SIGNAL_API_ERROR = "SIGNAL_API_ERROR";
export const SIGNAL_API_SUCCESS = "SIGNAL_API_SUCCESS";
export const NOTIFY_INFO = "NOTIFY_INFO";
export const NOTIFY_WARNING = "NOTIFY_WARNING";
export const NOTIFY_ERROR = "NOTIFY_ERROR";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";

export const LOAD_MENU_DETAILS_REQUESTED = "LOAD_MENU_DETAILS_REQUESTED";
export const LOAD_MENU_DETAILS_COMPLETED = "LOAD_MENU_DETAILS_COMPLETED";
export const SET_MENU_DETAIL_QUANTITY = "SET_MENU_DETAIL_QUANTITY";
export const MENU_DETAILS_CHANGED = "MENU_DETAILS_CHANGED";

export const EDIT_ORDER = "EDIT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const CLOSE_ORDER = "CLOSE_ORDER";
export const RESET_ORDER = "RESET_ORDER";
export const CONFIRM_ORDER = "CONFIRM_ORDER";
export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_CHANGED = "ORDER_CHANGED";
export const ORDER_PRINTED = "ORDER_PRINTED";
export const ORDER_DELETED = "ORDER_DELETED";
export const ORDER_CLOSED = "ORDER_CLOSED";
export const SET_ORDER_CUSTOMER = "SET_ORDER_CUSTOMER";
export const SET_ORDER_TABLE = "SET_ORDER_TABLE";
export const SET_ORDER_SEATS = "SET_ORDER_SEATS";
export const SET_ORDER_NOTES = "SET_ORDER_NOTES";
export const INCREMENT_ORDER_DETAIL_QUANTITY = "INCREMENT_ORDER_DETAIL_QUANTITY";

export const LOAD_ORDERS_LIST_REQUESTED = "LOAD_ORDERS_LIST_REQUESTED";
export const LOAD_ORDERS_LIST_COMPLETED = "LOAD_ORDERS_LIST_COMPLETED";
export const TOGGLE_ORDERS_LIST_FILTER_BY_USER = "TOGGLE_ORDERS_LIST_FILTER_BY_USER";
export const TOGGLE_ORDERS_LIST_FILTER_BY_STAND = "TOGGLE_ORDERS_LIST_FILTER_BY_STAND";
export const TOGGLE_ORDERS_LIST_FILTER_BY_STATUS = "TOGGLE_ORDERS_LIST_FILTER_BY_STATUS";
export const RESET_ORDER_SELECTION_FOR_AGGREGATION = "RESET_ORDER_SELECTION_FOR_AGGREGATION";
export const TOGGLE_ORDER_SELECTION_FOR_AGGREGATION = "TOGGLE_ORDER_SELECTION_FOR_AGGREGATION";
export const ORDER_DETAILS_AGGREGATION_REQUESTED = "ORDER_DETAILS_AGGREGATION_REQUESTED";
export const ORDER_DETAILS_AGGREGATION_COMPLETED = "ORDER_DETAILS_AGGREGATION_COMPLETED";

export const LOAD_SELECTED_ORDER_REQUESTED = "LOAD_SELECTED_ORDER_REQUESTED";
export const LOAD_SELECTED_ORDER_COMPLETED = "LOAD_SELECTED_ORDER_COMPLETED";

export const PRINT_REQUESTED = "PRINT_REQUESTED";
export const PRINT_COMPLETED = "PRINT_COMPLETED";

export const LOAD_NOTIFICATIONS_LIST_REQUESTED = "LOAD_NOTIFICATIONS_LIST_REQUESTED";
export const LOAD_NOTIFICATIONS_LIST_COMPLETED = "LOAD_NOTIFICATIONS_LIST_COMPLETED";

export const CALCULATE = "CALCULATE";

export const LOAD_DASHBOARD_DATA_REQUESTED = "LOAD_DASHBOARD_DATA_REQUESTED";
export const LOAD_DASHBOARD_DATA_COMPLETED = "LOAD_DASHBOARD_DATA_COMPLETED";

export const LOAD_SETTINGS_LIST_REQUESTED = "LOAD_SETTINGS_LIST_REQUESTED";
export const LOAD_SETTINGS_LIST_COMPLETED = "LOAD_SETTINGS_LIST_COMPLETED";
export const SET_SETTING_VALUE = "SET_SETTING_VALUE";

export const LOAD_STANDS_LIST_REQUESTED = "LOAD_STANDS_LIST_REQUESTED";
export const LOAD_STANDS_LIST_COMPLETED = "LOAD_STANDS_LIST_COMPLETED";

export const LOAD_USERS_LIST_REQUESTED = "LOAD_USERS_LIST_REQUESTED";
export const LOAD_USERS_LIST_COMPLETED = "LOAD_USERS_LIST_COMPLETED";
