export const SIGNIN_REQUESTED = "SIGNIN_REQUESTED";
export const SIGNIN_COMPLETED = "SIGNIN_COMPLETED";
export const SIGNOUT_REQUESTED = "SIGNOUT_REQUESTED";
export const SIGNOUT_COMPLETED = "SIGNOUT_COMPLETED";
export const SIGNUP_REQUESTED = "SIGNUP_REQUESTED";
export const SIGNUP_COMPLETED = "SIGNUP_COMPLETED";
export const LOAD_USER_DATA = "LOAD_USER_DATA";

export const LOADING_CHANGED = "LOADING_CHANGED";
export const SIGNAL_API_ERROR = "SIGNAL_API_ERROR";
export const NOTIFY_INFO = "NOTIFY_INFO";
export const NOTIFY_WARNING = "NOTIFY_WARNING";
export const NOTIFY_ERROR = "NOTIFY_ERROR";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";

export const LOAD_MENU_DETAILS_REQUESTED = "LOAD_MENU_DETAILS_REQUESTED";
export const LOAD_MENU_DETAILS_COMPLETED = "LOAD_MENU_DETAILS_COMPLETED";

export const CONNECT_SIGNALR = "CONNECT_SIGNALR";
export const DISCONNECT_SIGNALR = "DISCONNECT_SIGNALR";

export const CREATE_EMPTY_ORDER = "CREATE_EMPTY_ORDER";
export const EDIT_ORDER = "EDIT_ORDER";
export const RESET_ORDER = "RESET_ORDER";
export const CONFIRM_ORDER = "CONFIRM_ORDER";
export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_CHANGED = "ORDER_CHANGED";
export const ORDER_PRINTED = "ORDER_PRINTED";
export const SET_ORDER_TABLE = "SET_ORDER_TABLE";
export const SET_ORDER_TABLE_CATEGORY = "SET_ORDER_TABLE_CATEGORY";
export const SET_ORDER_SEATS = "SET_ORDER_SEATS";
export const SET_ORDER_NOTES = "SET_ORDER_NOTES";
export const INCREMENT_ORDER_DETAIL_QUANTITY =
  "INCREMENT_ORDER_DETAIL_QUANTITY";

export const LOAD_ORDERS_LIST_REQUESTED = "LOAD_ORDERS_LIST_REQUESTED";
export const LOAD_ORDERS_LIST_COMPLETED = "LOAD_ORDERS_LIST_COMPLETED";
export const INVALIDATE_ORDERS_LIST = "INVALIDATE_ORDERS_LIST";
export const TOGGLE_ORDERS_LIST_FILTER = "TOGGLE_ORDERS_LIST_FILTER";

export const LOAD_SELECTED_ORDER_REQUESTED = "LOAD_SELECTED_ORDER_REQUESTED";
export const LOAD_SELECTED_ORDER_COMPLETED = "LOAD_SELECTED_ORDER_COMPLETED";
export const INVALIDATE_SELECTED_ORDER = "INVALIDATE_SELECTED_ORDER";

export const PRINT_REQUESTED = "PRINT_REQUESTED";
export const PRINT_COMPLETED = "PRINT_COMPLETED";

export const LOAD_NOTIFICATIONS_LIST_REQUESTED = "LOAD_NOTIFICATIONS_LIST_REQUESTED";
export const LOAD_NOTIFICATIONS_LIST_COMPLETED = "LOAD_NOTIFICATIONS_LIST_COMPLETED";
export const INVALIDATE_NOTIFICATIONS_LIST = "INVALIDATE_NOTIFICATIONS_LIST";

export const CALCULATE = "CALCULATE";
