version: '3.7'

services:
  api:
    image: ${DOCKER_REGISTRY-}cappannahelperapi
    build:
      context: .
      dockerfile: CappannaHelper.Api/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - 58481:80
    links:
      - db:db

  db:
    image: ${DOCKER_REGISTRY-}postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/conf:/etc/postgresql
    ports:
        - 15432:5432

  pgadmin:
    image: dpage/pgadmin4:4.2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
        - 10080:80
    links:
      - db:db

volumes:
  postgres:

