version: '3.7'

services:
  api:
    image: ${DOCKER_REGISTRY-}cappannahelperapi
    build:
      context: .
      dockerfile: CappannaHelper.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - 58481:80