export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_COMPLETED = "LOGOUT_COMPLETED";
export const LOADING_CHANGED = "LOADING_CHANGED";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
