export const SIGNIN_REQUESTED = "SIGNIN_REQUESTED";
export const SIGNIN_COMPLETED = "SIGNIN_COMPLETED";
export const SIGNOUT_REQUESTED = "SIGNOUT_REQUESTED";
export const SIGNOUT_COMPLETED = "SIGNOUT_COMPLETED";
export const LOADING_CHANGED = "LOADING_CHANGED";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
export const LOAD_USER_DATA = "LOAD_USER_DATA";
