name: Build Api

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./src/cappanna-helper-api/
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        cache: false
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Publish
      run: dotnet publish -c Release --no-build --output publish/ CappannaHelper.Api
    - name: Create empty wwwroot folder
      run: |
        mkdir publish/wwroot
    - name: Create empty Persistence folder
      run: |
        mkdir publish/Persistence
    - name: Package Api
      uses: actions/upload-artifact@v4
      with:
        name: Api
        path: ./src/cappanna-helper-api/publish
