name: Build App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./src/cappanna-helper-app/
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies and build project
      run: |
        npm ci
        npm run build
    
  archive:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./src/cappanna-helper-app/
    steps:
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Filter files
        path: build
